name: update-homebrew-formula

on:
  release:
    types: [published]

jobs:
  homebrew-release:
    runs-on: macos-latest
    steps:
      - name: Release Homebrew Formula
        if: github.event.release.prerelease != true
        uses: garden-io/update-homebrew-action@v1
        with:
          packageName: 'cli'
          templatePath: 'Formula/baselime.rb'
          tapRepo: 'baselime/homebrew-tap'
          srcRepo: 'baselime/cli'
          authToken: ${{ secrets.GITHUB_TOKEN }}
