name: validate

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: rome/setup-rome@v0.4
        with:
          version: cli/v11.0.0-nightly.846c15e
      - run: rome ci .