name: validate

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: Lastin/setup-rome@v0.5
        with:
          version: 10.0.1
      - run: rome ci .